#!/usr/bin/env bash
# ─── generate-secrets.sh ───
# Generate a fresh .env with cryptographically random secrets.
# Safe to run multiple times — overwrites the file each time.
set -euo pipefail

ENV_FILE="${1:-.env}"

if [ -f "$ENV_FILE" ]; then
  echo "WARNING: $ENV_FILE already exists. Overwriting in 3s..."
  sleep 3
fi

gen() { openssl rand -base64 "$1" | tr -d '\n' ; }

set +u
cat > "$ENV_FILE" <<EOF
# Generated by scripts/generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit this file. Add it to .gitignore.

POSTGRES_USER=bheda
POSTGRES_PASSWORD=$(gen 32)
POSTGRES_DB=bheda
DATABASE_URL=postgresql+asyncpg://bheda:$(gen 32)@localhost:5432/bheda

REDIS_PASSWORD=$(gen 32)
REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379/0

MONGO_USER=bheda
MONGO_PASSWORD=$(gen 32)
MONGO_URL=mongodb://bheda:${MONGO_PASSWORD}@localhost:27017/bheda

SECRET_KEY=$(gen 48)
API_KEY=$(gen 32)
FLAG_SECRET=$(gen 48)

MODE=practice
RABBIT_HOLES_ENABLED=true
SCHEDULER_ENABLED=true
PROFILES_ENABLED=true
CTF_MAX_TEAM_SIZE=5
CTF_DEFAULT_EVENT_DURATION_HOURS=48

NEXT_PUBLIC_API_URL=http://localhost:8000

WAF_ENABLED=true
WAF_MODE=anomaly
TLS_LAB_ENABLED=true
LOG_LEVEL=INFO
EOF

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE with mode 0600."
echo "Edit docker-compose.yml / config/*.env / k8s manifests to source these."
