server {
    listen 44301 ssl;
    ssl_certificate /certs/self-signed/server.crt;
    ssl_certificate_key /certs/self-signed/server.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    location / { return 200 "BHEDA{tls_self_signed_ca}"; }
}
