server {
    listen 44302 ssl;
    ssl_certificate /certs/expired/server.crt;
    ssl_certificate_key /certs/expired/server.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    location / { return 200 "BHEDA{tls_expired_certificate}"; }
    location /backup/ {
        alias /certs/expired/;
        autoindex on;
    }
}
