server {
    listen 44305 ssl;
    ssl_certificate /certs/revoked/server.crt;
    ssl_certificate_key /certs/revoked/server.key;
    ssl_client_certificate /certs/ca/ca.crt;
    ssl_verify_client on;
    ssl_crl /certs/ca/ca.crt;
    ssl_stapling off;
    ssl_protocols TLSv1.2 TLSv1.3;
    location / { return 200 "BHEDA{tls_crl_disabled}"; }
}
