server {
    listen 44309 ssl;
    ssl_certificate /certs/self-signed/server.crt;
    ssl_certificate_key /certs/self-signed/server.key;
    ssl_protocols TLSv1.2;
    ssl_ciphers NULL;
    location / { return 200 "BHEDA{tls_null_cipher}"; }
}
