server {
    listen 44311 ssl;
    ssl_certificate /certs/self-signed/server.crt;
    ssl_certificate_key /certs/self-signed/server.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers AES128-SHA:!aNULL:!eNULL;
    location / { return 200 "BHEDA{tls_export_cipher}"; }
}
