server {
    listen 44312 ssl;
    ssl_certificate /certs/self-signed/server.crt;
    ssl_certificate_key /certs/self-signed/server.key;
    ssl_protocols TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL;
    # ssl_compression on;  # removed - unknown directive in nginx 1.24
    location / { return 200 "BHEDA{tls_compression_crime}"; }
}
