server {
    listen 44313 ssl;
    ssl_certificate /certs/self-signed/server.crt;
    ssl_certificate_key /certs/self-signed/server.key;
    ssl_protocols TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL;
    location / { return 200 "BHEDA{tls_heartbleed}"; }
    location /flag {
        return 200 "BHEDA{tls_heartbleed_memory_leak}";
    }
}
