server {
    listen 44316 ssl;
    ssl_certificate /certs/self-signed/server.crt;
    ssl_certificate_key /certs/self-signed/server.key;
    ssl_protocols TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL;
    gzip on;
    gzip_types text/plain;
    location / {
        add_header Set-Cookie "session=BHEDA{tls_breach_compression}";
        return 200 "Welcome. Your session is set.";
    }
}
